### ISSUE TITLE
collab?

### ISSUE THREAD

**Issue by eylles** [gotbletu/fzf-nova#1]
recently saw your video on zinger and got interested on it, rn i'm working on some stuff so i'll take the tiem to really understand how the script works but on the meantime i wanted to bring your attention towards something similar i had cobbled a while ago, https://github.com/eylles/fzf-copypasta

i also got a [fzf menu](https://github.com/eylles/fzfmenu) that i've had on the backburner as i want to ~~steal~~ port features from other launchers to it and i got interested in what fzf nova can do and how it can nicely integrate onto tmux as i want to bring some of that to it.

so i was wondering if we could collab on something to integrate some of the feature sets from the fzf menu type wrappers.

**Comment by gotbletu** [comment]
All the scripts on here are independent. It does not require fzf-nova to run. They are just regular shell scripts e.g you can do ./_zinger to execute it. Port any script you want, is free =)

I barely write scripts anymore, only when i got an idea.
I rather use other people finish programs, that would save me time.

**Comment by eylles** [comment]
thanks, i will try to port what i can.

**Comment by no1etal** [comment]
@eylles You may close the issue if resolved :)
